services:
  - type: web
    name: pneumonia-detection
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: model
      mountPath: /opt/render/project/src/model
      sizeGB: 1